import { roboto } from "@/components/font/fnt";
import type { Metadata } from "next";
import "./globals.css";
import Header from "./(ststic)/Header";



export const metadata: Metadata = {
  title: "Sticky Note",
  description: "Generated by Sticky Note",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <div className="max-w-7xl mx-auto px-2 md:px-6">
          {children}
        </div>
      </body>
    </html>
  );
}
